### ISSUE TITLE
[Feature Request] Intro/Outro detection using GPU?

### ISSUE THREAD

**Issue by Yankees4life** [jumoog/intro-skipper#156]
Any plans to implement detection using GPU decoding? I imagine that'll cut down the time for those with large libraries (like me).

Cheers

**Comment by jumoog** [comment]
Hardware-accelerated decoding is technically possible in ffmpeg, intro-skipper’s analysis workloads are fundamentally different from Jellyfin’s trickplay or playback pipelines. Most intro-skipper jobs decode only very small segments (or audio-only streams), and in practice they are not decode-bound. The dominant costs tend to be process startup, I/O, and the analysis filters themselves.

In many cases:

* Chromaprint never touches video at all.
* Blackframe detection decodes a *few seconds* of video.
* The CPU cost is dominated by **filter logic and analysis**, not decode throughput.

In real deployments, intro-skipper bottlenecks are usually:

* Disk I/O
* ffmpeg process spawn overhead

On systems with slower or single HDDs, overall performance is usually limited by file access rather than CPU throughput. In those cases, reducing the number of concurrent ffmpeg processes is more effective than offloading decode to the GPU, since multiple analysis processes competing for disk access tend to be the real bottleneck.

Additionally, some GPUs severely limit concurrent decode sessions (sometimes to a single stream). Using hwaccel for background analysis risks contending with playback or trickplay jobs, potentially degrading the user-visible experience rather than improving it.
