### ISSUE TITLE
[Bug]: Keeping one thread alive and slowing down Jellyfin

### ISSUE THREAD

**Issue by Schaka** [jumoog/intro-skipper#199]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

I made this report on jellyfin yesterday: https://github.com/jellyfin/jellyfin/issues/12084

Someone else mentioned, it may be caused by this plugin. Time-wise it would work out. The thread's age in htop lines up with the plugin's runtime (midnight) roughly.

I will say, I suspected the plugin, but restarted the server, triggered the task in the dashboard and couldn't reproduce it so I chucked it up to not being that. 

Maybe there is a minor difference between the automatic nightly job and the user triggered one upon button click in the dashboard that could cause this?

Edit: I noticed using the restart button in the dashboard doesn't work. The container needs to be restarted. Then all the jellyfin threads finally disappear from the host's htop and the problem is fixed until around the same time the next day. 

### Jellyfin install method

Docker, official Jellyfin image

### Container image/tag or Jellyfin version

jellyfin:latest, intro-skipper:latest

### Operating System

Debian 12

### Support Bundle

```shell
* Jellyfin version: 10.9.6
* Plugin version: 0.2.0+ddd538c29675
* Queue contents: 3493 episodes, 241 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
I don't think it's an issue with the plugin. Try setting the "Parallel library scan tasks limit" to 1 (instead of 0) in the Jellyfin general settings. If this doesn't resolve the issue, you might also consider lowering the "Maximum degree of parallelism" and "FFmpeg Threads" in the plugin settings. A value of 2 usually works well for both.

**Comment by AbandonedCart** [comment]
This is not the first time someone has suspected this plugin. The one thing that doesn't seem to have been done is a proper test. It would need to be confirmed that issue didn't exist without this plugin and did when this was the only plugin installed. 

When I performed that test, the plugin did not show any major impact. I can only speak on behalf of Mac and a native install, though. The one thing that seems to be related in every report of this issue is Docker. Whatever the cause is, it seems to be something specific to the Docker images.

**Comment by jumoog** [comment]
It is certainly a physical limit of, for example, mechanical hard disks

**Comment by rlauuzo** [comment]
I believe this is the same issue reported in https://github.com/jumoog/intro-skipper/issues/172. The root cause seems to be related to library scans that create excessive threads without properly closing them.

**Comment by cvium** [comment]
I would just like to point out that this plugin opens a bunch of Process instances in parallel without disposing of them nor their Output streams. This does not mean it permanently leaks memory or zombie processes, but it does mean that any managed and unmanaged resources aren't disposed until the GC calls the finalizer.

**Comment by AbandonedCart** [comment]
@cvium Thanks for the thorough investigation and keep in mind we are always open to pull requests if you have any suggestions for how to resolve the issue.

**Comment by cvium** [comment]
I don't use the plugin, so I don't think I'm the right person to do it :) I was just trying to understand some of the issue reports we have received. _Some_ of them had this plugin as a common denominator, some did not. It's hard to pin down the exact reason. I simply noticed some potential issues in the plugin. Maybe someone will feel motivated to take a closer look.

**Comment by jumoog** [comment]
The strange thing is that I do not have this problem on my system.

**Comment by Schaka** [comment]
I will say, after makng the multi thread adjustment you recommended, it hasn't happened again. It doesn't mean it's definitely the cause - I had way less activity on my server and jellyfin's memory usage is creeping up slowly for sure.

But it could very well be something like using multiple threads and only the main one ever getting cleaned up.

**Comment by AbandonedCart** [comment]
Since we lack any sort of evidence one way or the other and it doesn't really hurt anything, we can dispose of the processes and see if that makes any sort of difference. I found a lot of references to issues requiring `WaitForExit` with ffmpeg, but even all of the code attached to those issues gave no indication that it was being disposed. I would imagine the real issue is somewhere between the two. We don't dispose of it because that's never been a problem before and Docker somehow needs it to be disposed faster. The only thing I know for sure is that we need to either solve the issue or eliminate the suspicion because it's only going to keep coming up.

**Comment by jumoog** [comment]
> I would just like to point out that this plugin opens a bunch of Process instances in parallel without disposing of them nor their Output streams. This does not mean it permanently leaks memory or zombie processes, but it does mean that any managed and unmanaged resources aren't disposed until the GC calls the finalizer.
> 
> I think you may be too quick to assume it is an issue in Jellyfin and/or its images.
> 
> At these lines, the Process is created and its output is read, but neither are disposed. [`master`/ConfusedPolarBear.Plugin.IntroSkipper/FFmpegWrapper.cs#L418-L464](https://github.com/jumoog/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/FFmpegWrapper.cs?rgh-link-date=2024-06-14T05%3A24%3A07Z#L418-L464). The way this StreamReader is accessed causes it to enter SyncMode, and if you look at these lines in the runtime code, you will see that it does not dispose the Stream in that situation [dotnet/runtime@`5535e31`/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L897](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L897)

Thank you for your code review. The suggested improvements have been implemented in #200

**Comment by phyzical** [comment]
i just bumped my plugin version, ill report back in a few days to confirm memory usage has improved or not

**Comment by phyzical** [comment]
i dont think it has helped tbh. i have a feeling it really is something low level sadly...

![image](https://github.com/jumoog/intro-skipper/assets/5182053/7e169001-8f32-4167-9818-207edff788c5)

**Comment by AbandonedCart** [comment]
> i dont think it has helped tbh. i have a feeling it really is something low level sadly... (or not even something with this plugin)

There's no "low level" in the plugin, though. That would have to be in Jellyfin, ffmpeg, or .NET because a plugin runs on top of the existing software. It does not bring it's own set of binaries and libraries.

**Comment by phyzical** [comment]
sorry i should have said upstream, but yeah i feel like its OOS for the plugin with my testing so far

**Comment by jumoog** [comment]
From what I have seen, people are having the same problem and they are not using this plugin

**Comment by cvium** [comment]
> > i dont think it has helped tbh. i have a feeling it really is something low level sadly... (or not even something with this plugin)
> 
> There's no "low level" in the plugin, though. That would have to be in Jellyfin, ffmpeg, or .NET because a plugin runs on top of the existing software. It does not bring it's own set of binaries and libraries.

Generally speaking, a plugin can be as low level as it wants to be and bring whatever it wants to.

**Comment by AbandonedCart** [comment]
> Generally speaking, a plugin can be as low level as it wants to be and bring whatever it wants to.

Generally speaking, but **this** plugin doesn't. We made those changes you mentioned, despite having no evidence they were necessary. Perhaps you could reciprocate by looking into why Docker Jellyfin images seem to be the other common connection.

**Comment by AbandonedCart** [comment]
> From what I have seen, people are having the same problem and they are not using this plugin

It's an easy target. The closest we've come to a legitimate link between the plugin and the issue is that a number of reports came from users with it installed. It's one of the most commonly installed plugins, so statistically speaking, a lot of people with any issue will have it installed.

Ironically, the two possible causes proposed for the plugin have been that it either doesn't dispose the process or spawns too many. It hasn't explicitly disposed of the process since day one, meaning that far predates the issue. It does now, but that didn't solve it. The options to limit the process are some of the first changes we added during the revival of development. This means that either they also don't have any significance to the issue or nobody is actually trying them.

I stand by my original point, though. We can't isolate the issue if the best anyone can bring to the table is casting doubt. We need quantifiable results.

**Comment by Schaka** [comment]
Unfortunately no luck with 10.9.7 and the plugin after the stream closing fix.
Took way longer for it to happen again, but once it goes crazy with RAM and swaps, everything just slows down like crazy.

**Comment by AbandonedCart** [comment]
@Schaka You've been able to confirm it was the plugin causing it?

**Comment by Schaka** [comment]
@AbandonedCart no, I haven't. I need to run for longer periods without the plugin to see if it still occurs. It's been fine for days and then happened twice again this week

**Comment by jumoog** [comment]
sorry but i can't reproduce the problem

**Comment by Niximkk** [comment]
still happening btw

**Comment by jumoog** [comment]
> still happening btw

What happens? Is the memory usage growing?

**Comment by Schaka** [comment]
People were reporting that it's an endpoint Jellystat calls, but ultimately a bug in Jellyfin.
Streamystats apparently doesn't trigger this

**Comment by jumoog** [comment]
I've never had any problems. The kernel uses all available memory as a cache for files. Portainer shows this as used memory.
