### ISSUE TITLE
Add option to delay credit skip

### ISSUE THREAD

**Issue by CasuallyFilthy** [jumoog/intro-skipper#221]
Sometimes when automatically skipping credits, it will skip too early and cut off the end of an episode. Can a customizable delay be implemented similar to the intro skip delay?

**Comment by 000junichi** [comment]
I wish there was an option to manage ending fingerprints in the plugin settings. Make it happen please!

**Comment by AbandonedCart** [comment]
> I wish there was an option to manage credits fingerprints in the plugin settings. Make it happen please!

This is already issue #129 but this is a different issue.

**Comment by AbandonedCart** [comment]
@CasuallyFilthy I don’t see why it couldn’t but have you tried the latest version of the plugin? A lot of the logic for that was rewritten and I noticed the issue was more trying to have a workaround for an early skip than actually seeing a part of the credits (ie. The intro offset is usually used for the episode title screens). There is also #203 in the works that will help fine tune detection.

**Comment by CasuallyFilthy** [comment]
> @CasuallyFilthy I don’t see why it couldn’t but have you tried the latest version of the plugin? A lot of the logic for that was rewritten and I noticed the issue was more trying to have a workaround for an early skip than actually seeing a part of the credits (ie. The intro offset is usually used for the episode title screens). There is also #203 in the works that will help fine tune detection.

Version 0.2.0.13? I have not, I saw the plugin updated today or yesterday, but haven't restarted the server for it to take effect as I'm generating trickplay images and don't want to interrupt that. 

For what it's worth, seeing a couple seconds of the credits before it skips would give me confidence that I'm not missing anything due to the auto skip

**Comment by AbandonedCart** [comment]
That’s fair. I leave part of the intro to make sure I don’t miss an episode, so I can fully appreciate your logic.

**Comment by accountForIssues** [comment]
(Just found this plugin and wanna say a huge thank you. This improves the viewing experience so much.)

In addition to the option mentioned here, I would also like to request an option to leave a bit of the credits as well similar to the intro one.

Context: I use Kodi with Jellyfin and often when the credits are skipped, it skips _past_ the video length. This causes Kodi to behave as if the video is paused at the end instead of playing the next item. I can manually play the next one just fine. Or if I manually seek it just before the end, it then plays the next episode fine. There's no errors that I can see.

Since it was related to this, I thought to put it here. Lemme know if you want me to create another issue.

**Comment by AbandonedCart** [comment]
@rlauuzo Sounds like your workaround may have an unintended side effect on Kodi.

**Comment by CasuallyFilthy** [comment]
I have submitted a merge request for this issue (#235 ). I was able to add the functionality by examining the code for the Intro Playback Duration feature and consider this resolved.

**Comment by rlauuzo** [comment]
> (Just found this plugin and wanna say a huge thank you. This improves the viewing experience so much.)
> 
> In addition to the option mentioned here, I would also like to request an option to leave a bit of the credits as well similar to the intro one.
> 
> Context: I use Kodi with Jellyfin and often when the credits are skipped, it skips _past_ the video length. This causes Kodi to behave as if the video is paused at the end instead of playing the next item. I can manually play the next one just fine. Or if I manually seek it just before the end, it then plays the next episode fine. There's no errors that I can see.
> 
> Since it was related to this, I thought to put it here. Lemme know if you want me to create another issue.

Please check if the newest preview release fixes your issue: [Preview Release 10.9](https://github.com/jumoog/intro-skipper/releases/tag/10.9%2Fpreview).
